### ISSUE TITLE
Epic: Actor events implementation

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1048]
This issue tracks the implementation of FIP draft for Actor Events: https://github.com/filecoin-project/FIPs/pull/483.

## Basics

- [x] Common types in fvm_shared.
- [x] ~`validate` method in dagcbor codec to structurally validate event payloads~
	- [ ] https://github.com/ipld/libipld/issues/158
	- Moved to https://github.com/filecoin-project/ref-fvm/issues/1111.
- [x] `record_event` syscall in SDK and kernel; accumulation of events in CallManager.
- [x] Return events in receipts via Executor.
- [x] Snake through events via filecoin-ffi to client.
- [x] Gas hooks and (parameterized) price formulae for recording events.
- [X] ~Implement and integrate event store?~
	- Moved to https://github.com/filecoin-project/ref-fvm/issues/1108.

## EVM runtime integration

- [x] Implement LOG opcodes.

## Gas params

- [X] Parameterize gas for events.
	- Moved to https://github.com/filecoin-project/ref-fvm/issues/1109.

## PRs

- [x] ref-fvm
	- [x] https://github.com/filecoin-project/ref-fvm/pull/1049
- [x] builtin-actors
	- [x] https://github.com/filecoin-project/builtin-actors/pull/839
- [x] filecoin-ffi
	- [x] https://github.com/filecoin-project/filecoin-ffi/pull/332
- [x] fil-actor-utils
	- [x] https://github.com/filecoin-project/filecoin-actor-utils/pull/1
