### ISSUE TITLE
EVM: Tracking for native precompile hardening

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#1286]
- [ ] resolve_address
- [ ] lookup_address
- [ ] get_actor_type
- [ ] ~get_randomness~ (dropped)
- [ ] call_actor https://github.com/filecoin-project/builtin-actors/pull/867
    - [ ] assert readonly state transitions
    - [ ] value passed in call, but not in params and visa versa 
    - [ ] compare return value with evm CALL of same contract
    
Being marked "done" includes:
- ensure reverts are done carefully
- ensure known edge cases have comments or are fixed
- documentation is clear
- at least one test expecting a non-revert error (if applicable)

This issue doesn't track _all_ the hardening needed for native precompiles, but it should cover the basic cases as well as some potential edge cases not tracked in other issues.

**Comment by mriise** [comment]
> Should we have a list here of these "known edge cases"


It's a bit hard to write it down as part of this issue as they usually require context and I haven't gone through and determined what are edge cases. (should probably add "find edge cases")

**Comment by mriise** [comment]
oops

**Comment by Stebalien** [comment]
Closing in favor of:

https://github.com/filecoin-project/ref-fvm/issues/1393
https://github.com/filecoin-project/ref-fvm/issues/1392
https://github.com/filecoin-project/ref-fvm/issues/1391
https://github.com/filecoin-project/ref-fvm/issues/1390
