### ISSUE TITLE
Fix TODO::FVM comments in Lotus

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1446]
- [ ] Empty object assertion in [invoker.go](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/chain/vm/invoker.go#L294)
- [ ] Null rounds shouldn't ever be represented as tipsets with no blocks [URL](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/chain/types/tipset.go#L205)
- [ ] The contract installation and invocation can be lifted into utility methods [URL](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/itests/eth_deploy_test.go#L29)
- [ ] We can either skip the assertion if the msg has already landed, or pause mining between the embryo creation and this assertion [URL](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/itests/eth_deploy_test.go#L108)
- [ ] The right time to exit this loop isn't after 20 iterations, but when StateWaitMsg returns [URL](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/itests/eth_deploy_test.go#L121)

**Comment by maciejwitowski** [comment]
Will split them into separate issues.

**Comment by maciejwitowski** [comment]
Closing after splitting.
