### ISSUE TITLE
TODO in Lotus: fixes in ETH deploy test

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#1503]
- [ ] The contract installation and invocation can be lifted into utility methods [URL](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/itests/eth_deploy_test.go#L29)
- [ ] We can either skip the assertion if the msg has already landed, or pause mining between the embryo creation and this assertion [URL](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/itests/eth_deploy_test.go#L108)
- [ ] The right time to exit this loop isn't after 20 iterations, but when StateWaitMsg returns [URL](https://github.com/filecoin-project/lotus/blob/ntwk/hyperspace/itests/eth_deploy_test.go#L121)

**Comment by maciejwitowski** [comment]
@raulk I took these tests from `TODO::FVM`s in Lotus: do we absolutely need to land any of these in C.3?

**Comment by Stebalien** [comment]
@maciejwitowski what's the status here?

**Comment by maciejwitowski** [comment]
I'd say these itests improvements aren't priority now.
