### ISSUE TITLE
Epic: A minimal FVM and SDK

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#18]
Create a minimal FVM that implements the key concepts in the [architecture doc](https://github.com/filecoin-project/fvm-project/blob/main/01-architecture.md), concretely the Domains, Boundaries, Invocation Container, Syscall handlers, and the Call Stack Manager.

> Former `Runtime` interface: https://github.com/filecoin-project/specs-actors/blob/master/actors/runtime/runtime.go

## Breakdown

- [X] #11
- [x] skeleton of FVM to enable divide-and-conquer
- [x] #62 
- [x] implement state IO (blockstore)
- [x] implement invocation container
- [x] implement call stack manager
- [x] implement cross-actor sends (via the call stack manager)
- [x] implement exit codes and aborts 
- [x] #201
- [x] implement actor creation
- [x] implement actor deletion
- [x] implement randomness access
	- [x] from tickets
	- [x] from beacon
- [x] implement address resolution
- [x] implement caller validation
- [x] implement contextual getters
	- [x] getter for network version
	- [x] getter for base fee
	- [x] getter for current epoch
	- [x] getter for circulating supply
- [x] implement bridging with current crypto syscalls
- [x] ~export FVM entrypoints to be consumed from node implementations via FFI~ (actually part of #58)
