### ISSUE TITLE
Road to open sourcing this repo

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#181]
We are very close! Here's a burndown list of tasks to be completed before open sourcing:

### Functional

- [x] #57.

### Testing

- [x] Implement test vector runner #174.
- [x] Get the test vectors running.
- [x] Get the test vectors reporting success rate.
- [x] Get 1/3 of actors v6 test vectors passing.
- [ ] Open issues for missing unit and integration tests.

### Code quality / gardening

- [x] Agree on an import style and fix-up all imports.
- [x] Audit and improve docs for all key packages and components.
- [ ] Review and cleanup TODOs; make sure they are recorded as issues in the repo (could seek some automation).
- [X] Delete `_forest` source tree 👋 
	- https://github.com/filecoin-project/fvm/pull/211

### Repo health

- [x] Add `help-wanted` and `good-first-issue` labels to issues.
- [x] Add a `WALKTHROUGH.md` doc describing the most important flows and parts of the system. Example sections:
    - How messages are executed
    - How the bidirectional FFI works
    - Error handling
- [x] Spruce up README to make more welcoming with call to actions, link to WALKTHROUGH, FVM logo, etc.

## Out of scope

These items won't block the open sourcing; these can be finalized later:

- Integration of the FVM into Lotus.
- 100% success rate of actors v6 test vectors.
- #155.
- #176.
