### ISSUE TITLE
Epic: fix consensus critical issues in actors

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/ref-fvm#23]
https://hackmd.io/eThp9-pyR0WfLJjBynFntA?view#F1-Multisig-does-not-properly-handle-internal-runtime-errors-when-executing-transactions

@laudiacay is gonna fix things, starting with anything "immediately exploitable"

> **The content below is added by @raulk**

## Issue index

- [x] filecoin-project/builtin-actors#41
- [x] filecoin-project/ref-fvm#27
- [x] filecoin-project/ref-fvm#28
- [x] filecoin-project/ref-fvm#29
- [x] filecoin-project/ref-fvm#30
- [x] filecoin-project/ref-fvm#31
- [x] filecoin-project/ref-fvm#32
- [x] filecoin-project/ref-fvm#33
- [x] filecoin-project/ref-fvm#34
- [x] filecoin-project/ref-fvm#35
- [x] filecoin-project/ref-fvm#36
- [x] filecoin-project/ref-fvm#37
- [x] filecoin-project/ref-fvm#38
- [x] filecoin-project/ref-fvm#39
- [x] filecoin-project/ref-fvm#40
- [x] filecoin-project/ref-fvm#41
- [x] filecoin-project/ref-fvm#42
- [x] filecoin-project/ref-fvm#43
- [x] filecoin-project/ref-fvm#44
- [x] filecoin-project/ref-fvm#45
- [x] filecoin-project/ref-fvm#46
- [x] filecoin-project/ref-fvm#47
- [x] filecoin-project/ref-fvm#48
- [x] filecoin-project/ref-fvm#49
- [x] filecoin-project/ref-fvm#50
- [x] filecoin-project/ref-fvm#51
- [x] filecoin-project/ref-fvm#52
- [x] filecoin-project/ref-fvm#53
- [x] filecoin-project/ref-fvm#54
- [x] filecoin-project/ref-fvm#55
