### ISSUE TITLE
Optimize IPLD Operations

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#332]
- [x] Remove redundant copies from CGO.
- [ ] Use a dedicated thread in Go for message passing instead of directly calling with CGO. Calling from Rust to Go is _very_ slow as it effectively schedules a new goroutine per call.
- [x] Try an FVM-side read-cache. We should also play with _just_ caching the state-tree itself (but not actor state).
- [x] Optimize Flush: https://github.com/filecoin-project/ref-fvm/issues/331

**Comment by Stebalien** [comment]
>  Use a dedicated thread in Go for message passing instead of directly calling with CGO. Calling from Rust to Go is very slow as it effectively schedules a new goroutine per call.

Specifically, instead of loading blocks by calling into go:

1. Have go call into rust, then wait on a channel for a block request.
2. In rust, write block requests to this channel.

This should reduce the CGO overhead by ~10x by having all calls go from Go to Rust, instead of from Rust to Go. Of course, other scheduling issues could make this _slower_ in practice, so :man_shrugging:?

We could also skip calling from go to rust _entirely_ by blocking on some system-level mutex in Rust.... but that may be significantly harder.

**Comment by dignifiedquire** [comment]
@Stebalien can you point me at the main code paths where this is happening today? Is there a test/benchmark that already exists that shows the current preformance of the system (ideally isolated)

**Comment by Stebalien** [comment]
@dignifiedquire tried this and it was massively complicated and didn't help performance. The right way to do this is to move the state-store into rust and access it from go, but that's a refactor for another day.
