### ISSUE TITLE
FIP-0032: Re-implement gas tracker by delegating to wasmtime fuel

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#375]
## Context

Entirely depends on the data captured and analyzed as part of #333.

## Tasks

- [ ] Determine the ratio between execution gas and Filecoin gas: #333; let's call this `r`.
- [ ] Add fuel to the wasmtime instance equal to `gas_limit * r`.
- [ ] Make all syscalls use the [`consume_fuel`](https://docs.wasmtime.dev/api/wasmtime/struct.Store.html#method.consume_fuel) operation on the Store, dividing their original gas value by  `r`, rounding up (`ceil`).
- [ ] Handle wasmtime out of fuel traps by aborting with an `OutOfGas` error.
- [ ] Calculate the final `gas_used` (Filecoin gas).
- [ ] Make sure that `gas_used` reporting is consistent with Filecoin gas (and does not leak wasmtime fuel).

**Comment by raulk** [comment]
@Stebalien Can you review the task list here and see if it makes sense?

**Comment by raulk** [comment]
This landed in https://github.com/filecoin-project/ref-fvm/pull/452.
