### ISSUE TITLE
nv16 development checklist

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#530]
## Required for feature freeze

These are issues that affect code running in production.

- [ ] Audit third party dependencies (@Friedel Ziegelmayer)
    - 🔴  Consensus breaking for changes in actors (changes Code CID)
    - anyhow, etc.
- [x] Switch CBOR library
    - 🔴  Consensus breaking (changes Code CID)
    - https://github.com/filecoin-project/ref-fvm/pull/472
- [ ] https://github.com/filecoin-project/ref-fvm/pull/509
    - 🔴  Consensus breaking
- [x] Wasm bytecode instrumentation (@Magik6k)
    - 🔴  Consensus breaking
    - https://github.com/filecoin-project/ref-fvm/pull/494
    - Gas accounting (closes Wasmtime fuel accounting edge cases)
    - Stack accounting (closes Wasmtime stack accounting)
- [ ] Fatal error handling as generic exit code (@Stebalien)
    - 🔴  Consensus breaking
    - https://github.com/filecoin-project/ref-fvm/issues/508
- [ ] Second pass of wasmtime configuration review
    - 🟡  Probably not consensus breaking, but depends on config flags ultimately adjusted
    - @Magik6k or @Kubuxu (after gas parameters done)
- [x] Improve FFI safety (@Friedel Ziegelmayer)
    - 🟢  Not consensus breaking
    - https://github.com/filecoin-project/filecoin-ffi/pull/247
- [ ] Lotus: Gas estimation around upgrade
    - [https://github.com/filecoin-project/lotus/issues/8417](https://github.com/filecoin-project/lotus/issues/8417)
- [ ] Lotus: final bundling strategy
	- Sever ffi dependency on built-in actors
	- Static and dynamic bundle loading

## Not required for feature freeze

- [ ] Getting itests passing (@Dimitris Vyzovitis)
    - 🟡  Consensus breaking if changes made in actors
- [x] Test integration framework
    - 🟢  Not consensus breaking
    - https://github.com/filecoin-project/ref-fvm/pull/471
- [ ] Correctness tests using test integration framework
    - 🟢  Not consensus breaking
- [ ] Fuzzing CBOR and IPLD targets (next owner TBD)
    - 🟢  Not consensus breaking
- [ ] builtin-actors (Rust): 1:1 unit test parity with specs-actors (Go)
    - 🟢  Not consensus breaking
- [ ] builtin-actors (Rust): 1:1 integration test parity with specs-actors (Go)
    - 🟢  Not consensus breaking
