### ISSUE TITLE
nv16 development checklist

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#531]
## Required for feature freeze

> 🎉  Feature freeze is complete!

These are issues that affect code running in production.

- [x] Refactor go-based state accessors (@arajasek)
    - 🟢  Not consensus breaking
    - Agree on the new design: https://github.com/filecoin-project/lotus/issues/8607
    - Land:
      - [x] https://github.com/filecoin-project/lotus/pull/8534
      - [x] https://github.com/filecoin-project/go-state-types/pull/36 (needed by all other PRs)
      - [x] https://github.com/filecoin-project/specs-storage/pull/25
      - [x] https://github.com/filecoin-project/specs-actors/pull/1590
      - [x] https://github.com/filecoin-project/filecoin-ffi/pull/269
      - [x] https://github.com/filecoin-project/go-fil-markets/pull/705 (also needs FFI)
- [x] Catch panics (@Stebalien)
    - 🔴  Consensus breaking
    - #557 
    - #574
	- [x] Anything arising from crypto calls
	- [x] verify_post [assumes that passed-in randomness is exactly 32 bytes in length](https://github.com/filecoin-project/ref-fvm/blob/7bf6731c85a2c33e207214e90f407d891edff2cb/fvm/src/kernel/default.rs#L565-L566).
	- [x] #651
  		- [verify_post](https://github.com/filecoin-project/ref-fvm/blob/7bf6731c85a2c33e207214e90f407d891edff2cb/fvm/src/kernel/default.rs#L582)
  		- [verify_aggregate_seals](https://github.com/filecoin-project/ref-fvm/blob/7bf6731c85a2c33e207214e90f407d891edff2cb/fvm/src/kernel/default.rs#L688-L689)
  		- [verify_seal](https://github.com/filecoin-project/ref-fvm/blob/7bf6731c85a2c33e207214e90f407d891edff2cb/fvm/src/kernel/default.rs#L997-L998)
- [x] Merge breaking syscall changes to master (@raulk)
    - 🔴  Consensus breaking
    - Feature branch: https://github.com/filecoin-project/ref-fvm/tree/feat/syscall-changes
    - https://github.com/filecoin-project/ref-fvm/pull/533
    - https://github.com/filecoin-project/ref-fvm/pull/555, which includes:
    	- https://github.com/filecoin-project/ref-fvm/issues/542
    		- 🟢  Not consensus breaking (for M1; non-zero offsets aren't used)
- [x] https://github.com/filecoin-project/ref-fvm/issues/543
    - 🟡  Could be consensus breaking 
- [x] https://github.com/filecoin-project/ref-fvm/issues/552
    - 🟡  Could be consensus breaking 
- [x] Lotus: final bundling strategy (@vyzo + @raulk + @arajasek)
    - 🟢  Not consensus breaking
    - https://github.com/filecoin-project/lotus/pull/8642
	- Sever ffi dependency on built-in actors
	- Get rid of environment variable dance
	- Static and dynamic bundle loading
- [x] Second pass of wasmtime configuration review
    - 🟡  Probably not consensus breaking, but depends on config flags ultimately adjusted
    - #547.
- [x] Propagate gas outputs (@vyzo)
    - 🟢  Not consensus breaking
    - https://github.com/filecoin-project/filecoin-ffi/pull/275
    - https://github.com/filecoin-project/ref-fvm/pull/526
    - https://github.com/filecoin-project/lotus/pull/8593
- [x] Fatal error handling as generic exit code (@raulk)
    - 🔴  Consensus breaking
    - #548.
    - https://github.com/filecoin-project/ref-fvm/issues/508
- [x] Implement parameters for FIP-0032 (@raulk)
    - 🔴  Consensus breaking
- [x] https://github.com/filecoin-project/ref-fvm/pull/509
    - 🔴  Consensus breaking
- [x] Audit third party dependencies (@dignifiedquire)
    - 🔴  Consensus breaking for changes in actors (changes Code CID)
    - https://github.com/filecoin-project/ref-fvm/pull/532
    - https://github.com/filecoin-project/builtin-actors/pull/329
- [x] Switch CBOR library
    - 🔴  Consensus breaking (changes Code CID)
    - https://github.com/filecoin-project/ref-fvm/pull/472
- [x] Wasm bytecode instrumentation (@Magik6k)
    - 🔴  Consensus breaking
    - https://github.com/filecoin-project/ref-fvm/pull/494
    - Gas accounting (closes Wasmtime fuel accounting edge cases)
    - Stack accounting (closes Wasmtime stack accounting)
- [x] Lotus: Gas estimation around upgrade (@arajasek + @Kubuxu)
    - 🟢  Not consensus breaking
    - [https://github.com/filecoin-project/lotus/issues/8417](https://github.com/filecoin-project/lotus/issues/8417)
- [x] Improve FFI safety (@dignifiedquire)
    - 🟢  Not consensus breaking
    - https://github.com/filecoin-project/filecoin-ffi/pull/247
- [x] 🔴 Update `serde_ipld_dagcbor` to include https://github.com/ipld/serde_ipld_dagcbor/commit/cf04a8742936e7d03a4cc5f64bb83af399e7a998.
- [x]  🔴 `ipld::block_read` bug https://github.com/filecoin-project/ref-fvm/pull/584

## Releases
- [x] Actors v8 release
- [x] Actors v7 release
- [x] fvm crates release
- [x] ffi release
- [x] Lotus release

## Not required for feature freeze

**Fixes from these efforts will be included in bugfix releases.**

- [X] ~Size limits on actors data structures (user-input and tree) (needs new owner)~
    - Naturally limited by message params.
    - 🔴  Consensus breaking
    - CBOR gen applies imipicits limits to everything, we don't. is it an issue?
- [x] Getting itests passing (@vyzo)
    - 🟡  Consensus breaking if changes made in actors
- [x] Test integration framework
    - 🟢  Not consensus breaking
    - https://github.com/filecoin-project/ref-fvm/pull/471
- [x] Correctness tests using test integration framework
    - 🟢  Not consensus breaking
    - A initial set of integration tests have been contributed, targeting various Areas of Concern.
- [x] Fuzzing CBOR and IPLD targets (@Kubuxu)
    - 🟢  Not consensus breaking
- [X] builtin-actors (Rust): 1:1 unit test parity with specs-actors (Go) (@ZenGround0 + @lemmih)
    - 🟢  Not consensus breaking
- [X] builtin-actors (Rust): 1:1 integration test parity with specs-actors (Go) (@ZenGround0)
    - 🟢  Not consensus breaking
- [X] Internal audit.
    - 🟢  Not consensus breaking
- [X] External audit.
    - 🟢  Not consensus breaking
- [ ] https://github.com/filecoin-project/ref-fvm/issues/544
    - 🟢  Not consensus breaking
- [ ] filecoin-project/fvm-specs#86
    - 🟢  Not consensus breaking
- [x] [compute-state --html error](https://github.com/filecoin-project/lotus/issues/8636)
    - 🟢  Not consensus breaking
- [X] Fully-featured development bundles
- [ ] :yellow_circle: Double-check panic catching, especially with respect to cbor decoding and crypto (inside the FVM, not inside wasm).
- [ ] :yellow_circle: Double-check wasmtime error handling, possibly treating all errors as illegal instruction (instead of fatal).
- [X] Dual execution for debugging actors
	- 🟢 Not consensus breaking

**Comment by ZenGround0** [comment]
Actors bugs that need to be fixed/investigated/merged by feature freeze: 
* [Map delete behavior issu](https://github.com/filecoin-project/builtin-actors/issues/355) 
* [Paych limits PR](https://github.com/filecoin-project/builtin-actors/pull/350)
* [Record faults bug fix PR](https://github.com/filecoin-project/builtin-actors/pull/367)
* [Remove partitions bug fix PR](https://github.com/filecoin-project/builtin-actors/pull/362)

While its fine to discover and fix new bugs after freeze I think we should not call feature freeze when known actors bugs exist.
