### ISSUE TITLE
Epic: Lotus integration of reference FVM

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#58]
The goal is to integrate the reference FVM into Lotus. Initially the FVM will be activated through a feature flag `--fvm`. Only actors v6 and above will run on the FVM.

## Breakdown

- [ ] integrate FVM ~behind feature flag `--fvm`~ in a Lotus fork for now
- [X] ~integrate WASM bundles into lotus binary (go:embed?)~
    - Will be embedded in the FVM library. See https://github.com/filecoin-project/fvm/issues/131.
- [X] ~implement code loading from WASM bundles~
    - For M0, we won't be loading code from the node.
    - For M1+, we expect to access code as we access the state tree, so no special externsn are required.
- [ ] implement node-side of Boundary A (node to FVM).

**Comment by arajasek** [comment]
This is since completed
