### ISSUE TITLE
Syscall Testing Epic

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#585]
See https://github.com/filecoin-project/ref-fvm/pull/584 for an example. Take a look at the documentation in https://docs.rs/fvm_sdk/3.0.0-alpha.24/fvm_sdk/index.html for _expected_ behavior.

- [x] `ipld`
  - [ ] `block_open`
    - [x] basic functionality
    - [x] invalid cid
    - [x] invalid cid pointer
    - [ ] very large cid (check for ooms)
  - [x] `block_read`
  - [ ] `block_create`
    - [x] basic functionality
    - [x] forbidden codec.
    - [ ] large block (over 1MiB)
  - [ ] `block_stat`
    - [x] basic functionality
    - [x] returns the correct length/codec
    - [x] invalid id returns correct error
  - [ ] `block_link`
    - [x] basic functionality
    - [x] invalid id returns correct error
    - [x] cid buffer too short.
    - [x] invalid hash function/length returns correct errors
- [ ] `self`
  - [ ] `root`
    - [x] returns correct root
    - [x] returns the correct error after selfdestruct
  - [ ] `set_root`
    - [x] updates the root
    - [x] refuses to update the root when read-only
    - [x] returns the correct error after selfdestruct
  - [ ] `current_balance`
     - [x] returns correct balance
     - [x] returns 0 after selfdestruct
  - [ ] `self_destruct`
    - [x] doesn't work when read-only
    - [x] basic functionality
    - [x] fails when the recipient doesn't exist
    - [x] fails when the recipient is self
    - [ ] is idempotent
- [ ] `actor`
  - [x] `lookup_delegated_address`
  - [x] `resolve_address`
    - [x] can resolve addresses
    - [x] returns the correct errors on failure
  - [x] `get_actor_code_cid`
    - [x] correctly resolves code CIDs
    - [x] returns the correct error if an actor doesn't exist
  - [x] `create_actor`
  - [ ] `next_actor_address` (extend the `create_actor` tests)
    - [ ] returns the correct address
    - [ ] changes after actor deployment
  - ~`get_builtin_actor_type`~
- [ ] `crypto`
  - [x] `verify_signature`
  - [x] `hash`
  - [x] `recover_secp_public_key`
  - [x] `compute_unsealed_sector_cid`
  - [ ] `verify_consensus_fault` test with mocked extern?
  - ~`verify_seal`~ (requires params)
  - ~`verify_post`~ (requires params)
  - ~`verify_replica_update`~ (requires params)
  - ~`verify_aggregate_seal`~ (requires params)
  - ~`batch_verify_seals`~ (requires params)
- [ ] `rand` - test with mocked externs?
- [ ] `send` ?

**Comment by Stebalien** [comment]
Things to check for:

- Invalid arguments are correctly caught.
- Correct error codes are returned.
- Invariants are maintained (delete actor twice, delete, then set root, etc.).

**Comment by maciejwitowski** [comment]
@Stebalien Do we want to work on this in M2.1?

**Comment by Stebalien** [comment]
M2.1.5? This can land _after_ we start the audits, but this is some important testing debt.
