### ISSUE TITLE
Unit Tests Tracking Issue

### ISSUE THREAD

**Issue by mriise** [filecoin-project/ref-fvm#595]
## `DefaultKernel`

- [ ] `Kernel`
- [ ] `SelfOps`
- [ ] `IpldOps` https://github.com/filecoin-project/ref-fvm/pull/577
  - [ ] block_open
  - [x] block_create 
  - [x] block_link
  - [x] block_read
  - [x] block_stat
- [ ] `MessageOps`
- [ ] `SendOps`
- [ ] `CircSupplyOps`
- [ ] `CryptoOps`
- [ ] `GasOps`
- [ ] `NetworkOps`
- [ ] `RandomnessOps`
- [ ] `ActorOps`
- [ ] `DebugOps`

### TODOs for better quality tests
- [ ] macro testing functions for expected/documented error returns
- [ ] use `GasTracker` and make calls normally instead of reaching inside Kernel to call the functions on price_list
- [ ] split off boilerplate into functions/macros  

---

Tests purposely ignored till M2 (mostly because M1 is known to not care)
- Gas charge call counting for failed operations
- `IpldOps`
  - creation of invalid blocks
- Tests using NetworkVersion::V16
