### ISSUE TITLE
EPIC: Ethereum Addressing

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#898]
- [x] Implement f4 address support 
    - PR: https://github.com/filecoin-project/ref-fvm/pull/860
    - [x] Add a checksum
        - PR: https://github.com/filecoin-project/ref-fvm/pull/922
- [x] Implement an embryo actor
    - PR: https://github.com/filecoin-project/builtin-actors/pull/667
    - [x] And a bug fix https://github.com/filecoin-project/builtin-actors/pull/694
- [x] Integrate the embryo actor into the ref-fvm
    - PR: https://github.com/filecoin-project/ref-fvm/pull/897
- [x] Store the "predictable" address (f1/f3/f4) in the root "actor object"
    - PR: https://github.com/filecoin-project/builtin-actors/pull/743
- [x] Implement EAM actor.
    - PR: https://github.com/filecoin-project/builtin-actors/pull/695
