### ISSUE TITLE
FEVM Development Checklist

### ISSUE THREAD

**Issue by maciejwitowski** [filecoin-project/ref-fvm#936]
## Features
- [x] https://github.com/filecoin-project/ref-fvm/issues/903 **Planned release on Oct 21**
    - [x] F4 @Stebalien 
      - [x] https://github.com/filecoin-project/ref-fvm/issues/898
      - [x] https://github.com/filecoin-project/ref-fvm/issues/690
    - [x] https://github.com/filecoin-project/ref-fvm/issues/927
    - [x] https://github.com/filecoin-project/ref-fvm/issues/680
    - [x] https://github.com/filecoin-project/ref-fvm/issues/685 @vyzo 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/872 @vyzo 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/961

- [x] https://github.com/filecoin-project/ref-fvm/issues/939 **Planned release on Nov 14**
    - [x] https://github.com/filecoin-project/ref-fvm/issues/881 @stebalien
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1031 - @Stebalien
    - [x] https://github.com/filecoin-project/ref-fvm/issues/912 - @Stebalien
    - [x] https://github.com/filecoin-project/ref-fvm/issues/933 - @Stebalien
    - [x] https://github.com/filecoin-project/ref-fvm/issues/947 @mriise 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1021 @vyzo 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/884
    - [x] Ethereum logs
      - [x] https://github.com/filecoin-project/ref-fvm/issues/728
      - [x] https://github.com/filecoin-project/ref-fvm/issues/682
      - [x] https://github.com/filecoin-project/ref-fvm/issues/908
    - [x] https://github.com/filecoin-project/ref-fvm/issues/851 @aakoshh 
      - [x] https://github.com/filecoin-project/ref-fvm/issues/361
      - [x] https://github.com/filecoin-project/ref-fvm/issues/1011
      - [x] https://github.com/filecoin-project/ref-fvm/issues/1009
      - [x] https://github.com/filecoin-project/ref-fvm/issues/1055

- [x] https://github.com/filecoin-project/ref-fvm/issues/940
    - [x] https://github.com/filecoin-project/filecoin-ffi/issues/335
    - [x] https://github.com/filecoin-project/ref-fvm/issues/986 @vyzo
    - [x] https://github.com/filecoin-project/ref-fvm/issues/985 @vyzo 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1066 @mriise
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1018 @mriise 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1137 @ychiaoli18
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1136 @ychiaoli18 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1135 @ychiaoli18 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1076 @ychiaoli18
    - [x] https://github.com/filecoin-project/ref-fvm/issues/725 @Stebalien
    - [x] https://github.com/filecoin-project/builtin-actors/pull/646 - @vyzo
    - [x] https://github.com/filecoin-project/ref-fvm/issues/847 @vyzo 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/878 @vyzo  
    - [x] https://github.com/filecoin-project/ref-fvm/issues/966 @raulk
    - ~https://github.com/filecoin-project/ref-fvm/issues/1075 @aakoshh~ (half-implemented but not actually necessary)

- [ ] https://github.com/filecoin-project/ref-fvm/issues/1213
    - [x] https://github.com/filecoin-project/ref-fvm/issues/874 @vyzo
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1167 - @Stebalien 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1177 - @Stebalien
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1178 - @vyzo
    - [x] https://github.com/filecoin-project/ref-fvm/issues/956 @mriise 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1134 @mriise
    - [x] https://github.com/filecoin-project/builtin-actors/pull/897 - @stebalien
    - [x] https://github.com/filecoin-project/ref-fvm/issues/841 @vyzo 
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/980 @vyzo 
    - [ ] JSON-RPC @ychiaoli18 
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/1206
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/1196
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/1207
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/1189
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/1182
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/1208
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/1212
    - [ ] EVM Storage footprint @aakoshh (waiting on review by @vyzo)
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/892
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/891
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/890
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/859

- [ ] https://github.com/filecoin-project/ref-fvm/issues/1052
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1051 - @aakoshh 
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1174 - @Stebalien 
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1175
    - [x] https://github.com/filecoin-project/ref-fvm/issues/1171 - @mriise 
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1001 - @vyzo
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1056 - @stebalien
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/987 - @arajasek 
    - [x] https://github.com/filecoin-project/ref-fvm/issues/918
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1020
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1016 - @ychiaoli18
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/341 @aakoshh 
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1033 @ychiaoli18
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1201
    - [ ] https://github.com/filecoin-project/ref-fvm/issues/1198
    - [ ] Account Abstraction @Stebalien 
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/694
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/877 
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/640
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/721 
      - [ ] https://github.com/filecoin-project/ref-fvm/issues/877
## Post buildernet 
https://github.com/filecoin-project/ref-fvm/milestone/19

**Comment by maciejwitowski** [comment]
We are migrating to this board from now on https://github.com/orgs/filecoin-project/projects/54/views/26
