### ISSUE TITLE
EPIC: FVM Syscall Precompiles

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#947]
We need precompiles for various syscalls:

- [x] `actor::resolve_address`
- [x] `actor::lookup_address`
- [x] `actor::get_actor_code_cid`
- [x] `rand` - we should have a single "rand" precompile that can return both chain and beacon randomness.
- [ ] ~`vm::context` (actor IDs, etc).~ punting because we can get almost all of this information from other sources.

We don't need precompiles for:

- `crypto::verify_signature` - the Ethereum precompile is general-purpose enough to cover this.
- `crypto::hash`
    - sha256 and blake2b are already supported.
    - we can revisit this later.
- state related things
- miner-specific crypto functions

**Comment by maciejwitowski** [comment]
@mriise is it something you'll be able to handle as precompiles expert?
