### ISSUE TITLE
EPIC: Integrate f4 addressing into lotus

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#989]
- [x] Implement in go-address: https://github.com/filecoin-project/ref-fvm/issues/982
- [x] Future proof lotus: https://github.com/filecoin-project/lotus/pull/9515
- [ ] Add nv18 to go-state-types: https://github.com/filecoin-project/ref-fvm/issues/988
- [x] Integrate into the ethereum API: https://github.com/filecoin-project/ref-fvm/issues/983
- [x] Merge https://github.com/filecoin-project/ref-fvm/pull/990 (and release, bubble to the actors, etc.).
- [x] https://github.com/filecoin-project/ref-fvm/issues/992

**Comment by Stebalien** [comment]
Ok, all the address specific stuff is done. All that's left is to merge https://github.com/filecoin-project/go-state-types/pull/90.
